version: '3'

services:
  acurl:
    image: bbvalabs/acurl
  jwt-checker:
    image: bbvalabs/jwt-checker
  apicheck-proxy:
    image: bbvalabs/apicheck-proxy
    environment:
      - APICHECK_PROXY_LISTEN_ADDR=0.0.0.0
      - APICHECK_PROXY_LISTEN_PORT=9001
      - APICHECK_PROXY_ALLOWED_HOST=mysite.com
    ports:
      - "9001:9001"
  replay:
    image: bbvalabs/replay
    entrypoint: exec tail -f /dev/null 
  send-to-proxy:
    image: bbvalabs/send-to-proxy
    entrypoint: exec tail -f /dev/null 
  sensitive-data:
    image: bbvalabs/sensitive-data
    ports:
      - "9000:9000"
    entrypoint: sensitive-data --server 0.0.0.0:9000
  oas-checker:
    image: bbvalabs/oas-check
    entrypoint: exec tail -f /dev/null 
  openapiv2-lint:
    image: bbvalabs/openapiv2-lint
    entrypoint: exec tail -f /dev/null 
  openapiv3-lint:
    image: bbvalabs/openapiv3-lint
    entrypoint: exec tail -f /dev/null 
