name: CI - Docker testing image

on:
  push:
    branches: [ dev ]
    paths:
     - 'Dockerfile.testing'
     - '.dockerignore'
     - '.github/workflows/docker-testing-image.yml'
  pull_request:
    branches: [ dev ]
    paths:
     - 'Dockerfile.testing'
     - '.dockerignore'
     - '.github/workflows/docker-testing-image.yml'

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build docker image
        run: |
          docker build -t api-security-toolbox -f Dockerfile.testing .
  
