name: CI - Docker testing image

on:
  push:
    branches: [ dev ]
    paths:
     - 'Dockerfile.testing'
     - '.dockerignore'
     - '.github/workflows/docker-testing-image.yml'
  pull_request:
    branches: [ dev ]
    paths:
     - 'Dockerfile.testing'
     - '.dockerignore'
     - '.github/workflows/docker-testing-image.yml'

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --no-cache \
          -t api-security-toolbox:local \
          -f Dockerfile.testing \
          .

    # Run additional tests
    - name: Tests
      run: |-
        export TOOL_NAME="${TOOL_NAME:-bash}"
        docker run --rm \
          api-security-toolbox:local \
          which "$TOOL_NAME"; type "$TOOL_NAME"; file $(which "$TOOL_NAME")

