name: CI - Verify tools inside image

on:
  push:
    branches: [ main ]
    paths:
     - 'Dockerfile'
     - 'drafts/tools-list.txt'
     - 'drafts/verify-tools.py'
     - '.github/workflows/verify-tools.yml'
  pull_request:
    branches: [ main ]
    paths:
     - 'Dockerfile'
     - 'drafts/tools-list.txt'
     - 'drafts/verify-tools.py'
     - '.github/workflows/verify-tools.yml'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    # Checks-out our repository
    - name: Checkout
      uses: actions/checkout@v2

    # Pull the Docker Hub image
    - name: Pull
      run: |-
        docker pull docker.io/arainho/api-security-toolbox:latest

    # Run additional tests
    - name: Tests
      run: |-
        chmod -Rv 777 $PWD/drafts/
        docker run --rm \
               -v "$PWD/drafts:/tmp" \
               docker.io/arainho/api-security-toolbox:latest \
               sh -c "cd /tmp; python verify-tools.py"

    # Commit possible changed files back to the repository.
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply 'collect wordlists' auto-commit changes
