name: CI - Verify tools inside image

on:
  push:
    branches: [ main ]
    paths:
     - 'Dockerfile'
     - 'drafts/tools-list.txt'
     - '.github/workflows/verify-tools.yml'
  pull_request:
    branches: [ main ]
    paths:
     - 'Dockerfile'
     - 'drafts/tools-list.txt'
     - '.github/workflows/verify-tools.yml'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    # Checks-out our repository
    - name: Checkout
      uses: actions/checkout@v2

    # Pull the Docker Hub image
    - name: Pull
      run: |-
        docker pull docker.io/arainho/api-security-toolbox:latest

    # Run additional tests
    - name: Tests
      run: |-
        docker run --rm \
               -v "$PWD/drafts:/opt" \
               docker.io/arainho/api-security-toolbox:latest \
               python3 /opt/verify-tools.py
